accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name = "signup"), 
    path('login/', views.login_view, name = "login"),
    path('logout/', views.logout_view, name = "logout"),
]

articles/urls.py
from django.urls import path, include
from . import views
app_name = 'articles'
urlpatterns = [
    path('', views.articles_list.as_view(), name = "list"),
    path('create/', views.article_create.as_view(), name="create"),
    path( '<slug:slug>', views.article_detail.as_view(), name = "detail" ),
    path('update/<slug:slug>', views.article_update.as_view(), name="update"),
    path('delete/<slug:slug>', views.article_delete.as_view(), name="delete"),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('', article_views.articles_list.as_view(), name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default = 'defualt.png', blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return (self.body[:50]+'...')
    
    def get_absolute_url(self):
        return reverse('articles:list')
        

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user) 
            return redirect('articles:list')
    else:   
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            # log in  the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if( request.method == 'POST'):
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from . import forms
from .models import Article

# Create your views here.
class articles_list(ListView):
    model = Article
    queryset = Article.objects.all().order_by('-date')
    template_name = 'articles/articles_list.html'

# def articles_list(request):
#     article = Article.objects.all().order_by('-date')
#     return render(request, 'articles/articles_list.html', {'articles':article})

class article_detail(DetailView):
    model = Article
    slug_url_kwarg = 'slug'
    template_name = 'articles/article_detail.html'

# def article_detail(request, slug):
#     article = Article.objects.get(slug=slug)
#     return render(request, 'articles/article_detail.html', {'article': article})

# @login_required(login_url="/accounts/login/")
class article_create(CreateView):
    model = Article
    form_class = forms.CreateArticle
    template_name = 'articles/article_create.html'
    def post(self, request):
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
        
class article_update(UpdateView):
    model = Article
    slug_url_kwarg = 'slug'
    form_class = forms.CreateArticle
    template_name = 'articles/article_update.html'


class article_delete(DeleteView):
    model = Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy('articles:list')


# def article_create(request):
#     if request.method == 'POST':
#         form = forms.CreateArticle(request.POST, request.FILES)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             instance.author = request.user
#             instance.save()
#             return redirect('articles:list')
#     else:
#         form = forms.CreateArticle()
#     return render(request, 'articles/article_create.html', { 'form': form })

djangoproject/views.py
from django.http import HttpResponse 
from django.shortcuts import render

def home(request):
    # return HttpResponse('home')
    return render(request, 'home.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        
        {% if request.GET.next  %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button type="submit" value="Login">Login</button>
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" value="Signup">Sign up</button>
    </form>
    
    
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="create-article">
    <h2>Create New Article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <div class="container-center">
            <button type="submit" value="Create">Create</button>
        </div>
        
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_delete.html
{% extends 'base_layout.html'%}

{% block content %}
    {% if user.id == article.author.id %}
        <form class="site-form" method="post">
            <h2> Delete {{ article.title }} ?</h2>
            {% csrf_token %}
                <button>Delete</button>
            
        </form>
    {% endif %}

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html'%}

{% block content %}
<div class="article-detail">
    <img src="{{article.thumb.url}}"/>
    <h2>{{ article.title }}</h2>
    <p>{{ article.body }}</p>
    <small>{{ article.date }}</small>
    <br>
    <br>    
    {% if user.id == article.author.id %}
        <small><a href="{% url 'articles:update' slug=article.slug%}" style="color: white;">[Edit]</a></small>
        <small><a href="{% url 'articles:delete' slug=article.slug%}" style="color: white;">[Delete]</a></small>
    {% endif %}
</div>

{% endblock %}

articles/templates/articles/article_update.html
{% extends 'base_layout.html' %}

{% block content %}

{% if user.id == article.author.id %}
    <div class="create-article">
        <h2>Update Article</h2>
        <form class="site-form" action="{% url 'articles:update' slug=article.slug %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <div class="container-center">
                <button type="submit" value="Update">Update</button>
            </div>
            
        </form>
    </div>
{% endif %}
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/articles_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in object_list %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p class="date">{{ article.date }}</p>
            <br>
            <br>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <p>Learning Django so that you can express</p>
</body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="https://kit.fontawesome.com/2f886ed242.js" crossorigin="anonymous"></script>
    <title>Articles</title>
</head>
<body>
    <div class="header-color">
        <header class="wrapper">
            <h1><a href="{% url 'home' %}" ><i class="icon fas fa-blog"><p class="icon-head"> Blogger's Stop</p></i></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <form class="logout-link" action = "{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </li>
                        <li><a href="{% url 'articles:create' %}" class="highlight" >New Article</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
    </div>
    <div class='wrapper'>
        {% block content %}
        {% endblock %}
    </div>    
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Blawg</title>
</head>
<body>
    <h1>Welcome to people's blawggs.</h1>
</body>
</html>